// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2P9BAG1THla6JwpSfM_iCaYloMtufMBA',
    appId: '1:762370307959:android:098cb3a66d7283587e5372',
    messagingSenderId: '762370307959',
    projectId: 'travelclup-e8728',
    storageBucket: 'travelclup-e8728.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmAx8KC7CXxqr7WGzlzHZ8vT3E-ZmhgP8',
    appId: '1:762370307959:ios:ba934df1abae70187e5372',
    messagingSenderId: '762370307959',
    projectId: 'travelclup-e8728',
    storageBucket: 'travelclup-e8728.firebasestorage.app',
    androidClientId: '762370307959-9e3molrdgm5tafas44lbem0d0q016lvm.apps.googleusercontent.com',
    iosClientId: '762370307959-9e9if0bve4gs58stdkg3lj278r8cvenp.apps.googleusercontent.com',
    iosBundleId: 'com.topbusiness.travelclub',
  );
}
